name: AI CI

on:
  push:
    paths:
      - 'ai/**'
  pull_request:
    paths:
      - 'ai/**'

jobs:
  build:
    uses: negretenico/GithubWorkflows/.github/workflows/python_build.yaml@main
    with:
      working_directory: ai
    secrets: inherit

  docker:
    needs: build
    uses: negretenico/GithubWorkflows/.github/workflows/docker_build.yaml@main
    with:
      working_directory: ai
      service_name: ai
    secrets: inherit
